# -*- coding: utf-8 -*-
"""Factorielle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14makIdgKRPJCnLCJ307LwBHcnv06S_z2
"""

def factorielle(n, result = 1):
  while n > 0:
    result *= n
    n -= 1
    return factorielle(n, result)
  return result

factorielle(5)