# -*- coding: utf-8 -*-
"""Polynome.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qVgjA3vLHkurW8bNBVOgpmk0FIvlPfK6
"""


def polynom(x):
    return x ** 3 - 1.5 * x ** 2 - 6 * x + 5


polynom(5)
